return                      

{
	cs2dCommands = {
		"addhook",
		"ai_aim",
		"ai_attack",
		"ai_build",
		"ai_buy",
		"ai_debug",
		"ai_drop",
		"ai_findtarget",
		"ai_freeline",
		"ai_goto",
		"ai_iattack",
		"ai_move",
		"ai_radio",
		"ai_reload",
		"ai_respawn",
		"ai_rotate",
		"ai_say",
		"ai_sayteam",
		"ai_selectweapon",
		"ai_spray",
		"ai_use",
		"closehostage",
		"closeitems",
		"closeobjects",
		"entity",
		"entitylist",
		"freehook",
		"freeimage",
		"freetimer",
		"funcs",
		"game",
		"hostage",
		"image",
		"imagealpha",
		"imageblend",
		"imagecolor",
		"imagehitzone",
		"imagepos",
		"imagescale",
		"inentityzone",
		"item",
		"itemtype",
		"map",
		"menu",
		"msg",
		"msg2",
		"object",
		"objectat",
		"parse",
		"player",
		"playerweapons",
		"projectile",
		"projectilelist",
		"randomentity",
		"randomhostage",
		"reqcld",
		"setentityaistate",
		"sethookstate",
		"stats",
		"tile",
		"timer",
		"tween_alpha",
		"tween_color",
		"tween_move",
		"tween_rotate",
		"tween_rotateconstantly",
		"tween_scale",
		"vars"
	},
	
	cs2dHooks = {
		{"always"},
		{"attack", player = {1}},
		{"attack2", player = {1}},
		{"bombdefuse", player = {1}},
		{"bombexplode", player = {1}},
		{"bombplant", player = {1}},
		{"break", player = {3}},
		{"build", player = {1}},
		{"buildattempt", player = {1}},
		{"buy", player = {1}},
		{"clientdata", player = {1}},
		{"collect", player = {1}},
		{"die", player = {1, 2}},
		{"dominate", player = {1}},
		{"drop", player = {1}},
		{"endround"},
		{"flagcapture", player = {1}},
		{"flagtake", player = {1}},
		{"flashlight", player = {1}},
		{"hit", player = {1, 2}},
		{"hitzone", player = {2}},
		{"hostagerescue", player = {1}},
		{"join", player = {1}},
		{"kill", player = {1, 2}},
		{"leave", player = {1}},
		{"log"},
		{"mapchange"},
		{"menu", player = {1}},
		{"minute"},
		{"move", player = {1}},
		{"movetile", player = {1}},
		{"ms100"},
		{"name", player = {1}},
		{"objectdamage", player = {3}},
		{"objectkill", player = {2}},
		{"objectupgrade", player = {2}},
		{"parse"},
		{"projectile", player = {1}},
		{"radio", player = {1}},
		{"rcon", player = {2}},
		{"reload", player = {1}},
		{"say", player = {1}},
		{"sayteam", player = {1}},
		{"second"},
		{"select", player = {1}},
		{"serveraction", player = {1}},
		{"shieldhit", player = {1, 2}},
		{"spawn", player = {1}},
		{"spray", player = {1}},
		{"startround"},
		{"startround_prespawn"},
		{"suicide", player = {1}},
		{"team", player = {1}},
		{"trigger"},
		{"triggerentity"},
		{"use", player = {1}},
		{"usebutton", player = {1}},
		{"vipescape", player = {1}},
		{"vote", player = {1}},
		{"walkover", player = {1}}
	}
}